name: Databricks Multi-Environment Deployment

on:
  push:
    paths-ignore:
      - .github/**
      - README.md
      - docs/**
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy'
        required: true
        type: choice
        options:
          - development
          - uat
          - production
          - all

jobs:
  # ----------------------
  # VALIDATION & TESTS
  # ----------------------
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Validate syntax
        run: |
          echo "✅ Validating Python syntax..."
          # python -m py_compile $(find . -name "*.ipynb" -not -path "./venv/*")
      
      - name: Check for secrets in code
        run: |
          echo "🔍 Checking for exposed secrets..."
          if grep -r "password\|secret\|token" --include="*.py" --include="*.sql" .; then
            echo "⚠️ Warning: Potential secrets found in code"
          fi
      
      - name: Deployment summary
        run: |
          echo "📋 Deployment Summary:"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          echo "Timestamp: $(date)"

  # ----------------------
  # DEPLOY TO DEV
  # ----------------------
  deploy-dev:
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.environment == 'development' || github.event.inputs.environment == 'all'
    environment: 
      name: development
      # url: ${{ secrets.DEV_DEPLOYMENT_URL }}
    
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEVELOPMENT_TOKEN }}
      REPO_PATH: /Workspace/Repos/naman.doshi@datacurate.ai/AOC_DEV_FOLDER
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      
      - name: Pre-deployment validation
        run: |
          echo "🔍 Pre-deployment checks for DEV..."
          echo "Target repo: ${{ env.REPO_PATH }}"
          echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
          
          # Verify Databricks connection
          databricks repos list --output json | jq '.' || echo "⚠️ Warning: Could not list repos"
      
      - name: Update Databricks Repo (DEV)
        run: |
          echo "🚀 Deploying to DEV environment..."
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch.outputs.branch }}"
      
      - name: Post-deployment validation
        run: |
          echo "✅ DEV deployment completed successfully"
          echo "Deployment time: $(date)"
      
      - name: Deployment notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ DEV Deployment Successful"
          else
            echo "❌ DEV Deployment Failed"
          fi

  # ----------------------
  # DEPLOY TO UAT
  # ----------------------
  deploy-uat:
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && needs.deploy-dev.result == 'success') || 
      github.event.inputs.environment == 'uat' || 
      github.event.inputs.environment == 'all'
    environment: 
      name: uat
      # url: ${{ secrets.DEV_DEPLOYMENT_URL }}
    
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEVELOPMENT_TOKEN }}
      REPO_PATH: /Workspace/Repos/naman.doshi@datacurate.ai/AOC_UAT_FOLDER
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      
      - name: Pre-deployment validation
        run: |
          echo "🔍 Pre-deployment checks for UAT..."
          echo "Target repo: ${{ env.REPO_PATH }}"
          echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
          echo ""
          echo "⏳ Waiting for manual approval from UAT reviewers..."
      
      - name: Update Databricks Repo (UAT)
        run: |
          echo "🚀 Deploying to UAT environment..."
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch.outputs.branch }}"
      
      - name: Post-deployment validation
        run: |
          echo "✅ UAT deployment completed successfully"
          echo "Deployment time: $(date)"
          echo ""
          echo "📝 Next Steps:"
          echo "  1. Verify UAT deployment"
          echo "  2. Run UAT test suite"
          echo "  3. Get stakeholder sign-off"
          echo "  4. Proceed to PROD deployment after approval"
      
      - name: Deployment notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ UAT Deployment Successful"
          else
            echo "❌ UAT Deployment Failed"
          fi

  # ----------------------
  # DEPLOY TO PROD
  # ----------------------
  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && needs.deploy-uat.result == 'success') || 
      github.event.inputs.environment == 'production' || 
      github.event.inputs.environment == 'all'
    environment: 
      name: production
      # url: ${{ secrets.DEV_DEPLOYMENT_URL }}
    
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEVELOPMENT_TOKEN }}
      REPO_PATH: /Workspace/Repos/naman.doshi@datacurate.ai/AOC_PROD_FOLDER
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      
      - name: Pre-deployment validation
        run: |
          echo "⚠️  PRODUCTION DEPLOYMENT INITIATED"
          echo "================================================"
          echo "Target repo: ${{ env.REPO_PATH }}"
          echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
          echo "Commit: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Timestamp: $(date)"
          echo "================================================"
          echo ""
          echo "⏳ Waiting for manual approval from authorized personnel..."
          echo ""
          echo "Deployment checklist:"
          echo "  ☑ DEV deployment successful"
          echo "  ☑ UAT deployment successful"
          echo "  ⏳ Waiting for PROD approval"
      
      - name: Create deployment backup point
        run: |
          echo "💾 Creating backup reference..."
          echo "Previous commit: $(git rev-parse HEAD~1)"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Backup tag: backup-prod-$(date +%Y%m%d-%H%M%S)"
      
      - name: Update Databricks Repo (PROD)
        run: |
          echo "🚀 Deploying to PRODUCTION environment..."
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch.outputs.branch }}"
      
      - name: Post-deployment validation
        run: |
          echo "✅ PRODUCTION deployment completed successfully"
          echo "================================================"
          echo "Deployment completed at: $(date)"
          echo "Environment: PRODUCTION"
          echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
          echo "================================================"
          echo ""
          echo "📝 Post-deployment tasks:"
          echo "  1. Monitor application logs"
          echo "  2. Verify critical workflows"
          echo "  3. Check monitoring dashboards"
          echo "  4. Notify stakeholders"
      
      - name: Deployment notification
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ ✅ ✅ PRODUCTION Deployment Successful ✅ ✅ ✅"
          else
            echo "❌ ❌ ❌ PRODUCTION Deployment Failed ❌ ❌ ❌"
          fi
      
      - name: Create deployment tag
        if: success()
        run: |
          TAG_NAME="prod-release-$(date +%Y%m%d-%H%M%S)"
          echo "🏷️  Creating deployment tag: $TAG_NAME"
          git tag -a "$TAG_NAME" -m "Production deployment on $(date)"
          echo "Tag created successfully"

  # ----------------------
  # DEPLOYMENT SUMMARY
  # ----------------------
  deployment-summary:
    needs: [deploy-dev, deploy-uat, deploy-prod]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Generate deployment report
        run: |
          echo "=========================================="
          echo "       DEPLOYMENT SUMMARY REPORT"
          echo "=========================================="
          echo ""
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Trigger: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo ""
          echo "Environment Status:"
          echo "  DEV:  ${{ needs.deploy-dev.result }}"
          echo "  UAT:  ${{ needs.deploy-uat.result }}"
          echo "  PROD: ${{ needs.deploy-prod.result }}"
          echo ""
          echo "Completed at: $(date)"
          echo "=========================================="
