name: main

on:
  push:
    paths-ignore:
      - .github/**
    branches:
      - main

  workflow_dispatch:

jobs:
  # ----------------------
  # DEPLOY TO DEV
  # ----------------------
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development

    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEVELOPMENT_TOKEN }}
      REPO_PATH: /Workspace/Repos/naman.doshi@datacurate.ai/AOC_DEV_FOLDER
      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo (DEV)
        run: |
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch.outputs.branch }}" \

  # ----------------------
  # DEPLOY TO UAT
  # ----------------------
  deploy-uat:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: uat

    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEVELOPMENT_TOKEN }}
      REPO_PATH: /Workspace/Repos/naman.doshi@datacurate.ai/AOC_UAT_FOLDER

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo (UAT)
        run: |
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch.outputs.branch }}" \

  # ----------------------
  # DEPLOY TO PROD
  # ----------------------
  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: production

    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEVELOPMENT_TOKEN }}
      REPO_PATH: /Workspace/Repos/naman.doshi@datacurate.ai/AOC_PROD_FOLDER

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo (PROD)
        run: |
          databricks repos update "${{ env.REPO_PATH }}" \
            --branch "${{ steps.extract_branch.outputs.branch }}" \
